apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucontainer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucontain
  template:
    metadata:
      labels:
        app: ucontain
    spec:
      containers:
      - name: ucontain
        image: 753770582481.dkr.ecr.us-east-1.amazonaws.com/acontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ucontain
    k8s-app: ucontain
  name: ucontain
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: ucontain
